// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_test
int rcpp_test(Rcpp::IntegerVector input);
RcppExport SEXP _libfuzzerr_rcpp_test(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_test(input));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_libfuzzerr_rcpp_test", (DL_FUNC) &_libfuzzerr_rcpp_test, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_libfuzzerr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
